"""add certificados to curriculos

Revision ID: c8f7d6e5a9b1
Revises: b7c9a8f6d4e2
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f7d6e5a9b1'
down_revision = 'b7c9a8f6d4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculos', sa.Column('certificados', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculos', 'certificados')
    # ### end Alembic commands ###
